export const groupObject = [
  [
    {
      name: "ალქესანდრე ჭანკვეტაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ვაჩე კაკალაშვილი ",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ზაზა ბორისოვი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი ხუნდაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი მამულაიძე ",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ნიკა მუსერიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი გელაშვილი ",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი გოგოლაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი ჯოხაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ილია ზაქარაიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიგა ყიფიანი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "იოანე სარიშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა სიჭინავა",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა ნავროზაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
  ],
  [
    {
      name: "შიო ელიკაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "თემო ველიჯანაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ანდრია ღადუაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ნიკოლოზ ჩაგანავა",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ბუბა ებრალიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა გიორგაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "დაჩი ჯაჯანაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ბექა ბეჟანიშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ნოდიკო ბეჟანიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "დათო მელიქიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლაზაღე ღოღობერიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "დავით მეფარიშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლაზრე ღოღობერიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
  ],

  [
    {
      name: "კონსტანტინე პაპავა",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "კესანე ბრეგვაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა დათიაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა რაზმაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ანდრია ჯანეზაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა ოშორიზე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი წიკლაური",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ანდრია დვალი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გუგა აკოლაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "დავიდ დუმბაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ნიკოლოზ ტატიუაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "დემეტრე არეშიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "აკაკი წერეთელი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "მათე კუკუტარია",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
  ],

  [
    { name: "ლადო ნიჟარაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა ფიფია", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი ჩიღვინაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გურამ გელხაური", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გელუკა გენებაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა ტოკლიკიშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკა მალაყმაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა ციხელაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ელენე გაფრინდაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკოლოზ ქათამაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი უძილაური", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი ქრისტესიაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკა ბლიაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა შუკვანი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ანდრია ცაცუა", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა კელეპტრიშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა სუარიშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "დავით ლიპარტელიანი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გაბო დუმბაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ანა კაპანაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "რეზი ხარებავა", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნინო ზარდიაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ზურა დავითაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "დავით ქარაქუსოვი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკოლოზ ანთაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი გურიელი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "თორნიკე მღებლიშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "საბა ლაცაბიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა ოყროშიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა გვილავა", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა პიტნავა", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი კოსტავა", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა სურმანიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "რომან მაღრაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკა მაღლაფერიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "პაატა ცუცქირიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკოლოზ მელიჯანაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "დავით ბერკაცაშვილი", score: 0, classwork: 0, extraProjects: 0 },
  ],

  [
    { name: "ცოტნე გულბანი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "სანდრო სიუკაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ირაკლი ოზაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი დათაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი ტლაშაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი აბუაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი მანაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა მეტრეველი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლიზა ღიბრაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკოლოზ პეტრიაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "აპოლონ ასანიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "თორნიკე ჟუჟნიაშვილიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ბარბარე შარიქაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "რომიკო აბესაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ჯაბა ბეგიაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი ტატიაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "საბა ბეგიაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "უმარ აბუბაკაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "დათო მიქელაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნათია კიკვაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ბექა ბერაია", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი ომანაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "გიორგი გამლდია", score: 0, classwork: 0, extraProjects: 0 },
  ],
];
