export const groupObject = [
  [
    {
      name: "ალქესანდრე ჭანკვეტაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ვაჩე კაკალაშვილი ",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ზაზა ბორისოვი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი ხუნდაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი მამულაიძე ",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ნიკა მუსერიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი გელაშვილი ",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი გოგოლაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი ჯოხაძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ილია ზაქარაიძე",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიგა ყიფიანი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "იოანე სარიშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა სიჭინავა",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა ნავროზაშვილი",
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
  ],
  [{
    name: "საბა წიქარიშვილი",
    score: 150,
    classwork: 50,
    extraProjects: 100,
  },
  {
    name: "შიო ეაშვილი",
    score: 200,
    classwork: 80,
    extraProjects: 120,
  },
  {
    name: "თემო ველიჯანაშვილი",
    score: 170,
    classwork: 50,
    extraProjects: 120,
  },
  {
    name: "ანდრია ღადუაშვილი",
    score: 0,
    classwork: 0,
    extraProjects: 0,
  },
  {
    name: "ნიკოლოზ ჩაგანავა",
    score: 170,
    classwork: 50,
    extraProjects: 120,
  },
  {
    name: "ბუბა ებრალიძე",
    score: 50,
    classwork: 50,
    extraProjects: 0,
  },
  {
    name: "ლუკა გიორგაძე",
    score: 50,
    classwork: 50,
    extraProjects: 0,
  },
  {
    name: "დაჩი ჯაჯანაშვილი",
    score: 110,
    classwork: 50,
    extraProjects: 60,
  },
  {
    name: "ბექა ბეჟანიშვილი",
    score: 50,
    classwork: 50,
    extraProjects: 0,
  },
  {
    name: "გიგა ყიფიანი",
    score: 50,
    classwork: 50,
    extraProjects: 0,
  },
  {
    name: "ლაზრე ღოღობერიძე",
    score: 0,
    classwork: 0,
    extraProjects: 0,
  },
  ],
  [
    {
      name: "კონსტანტინე პაპავა",
      score: 210,
      classwork: 110,
      extraProjects: 100,
    },
    {
      name: "კესანე ბრეგვაძე",
      score: 25,
      classwork: 25,
      extraProjects: 0,
    },
    {
      name: "ლუკა დათიაშვილი",
      score: 65,
      classwork: 65,
      extraProjects: 0,
    },
    {
      name: "ლუკა რაზმაძე",
      score: 25,
      classwork: 25,
      extraProjects: 0,
    },
    {
      name: "ანდრია ჯანეზაშვილი",
      score: 185,
      classwork: 85,
      extraProjects: 100,
    },
    {
      name: "ლუკა ოშორიზე",
      score: 100,
      classwork: 100,
      extraProjects: 0,
    },
    {
      name: "გიორგი წიკლაური",
      score: 15,
      classwork: 15,
      extraProjects: 0,
    },
    {
      name: "ანარია დვალი",
      score: 25,
      classwork: 25,
      extraProjects: 0,
    },
    {
      name: "გუგა აკოლაშვილი",
      score: 80,
      classwork: 80,
      extraProjects: 0,
    },
    {
      name: "დავიდ დუმბაძე",
      score: 50,
      classwork: 50,
      extraProjects: 0,
    },
    {
      name: "დემეტრე ცეცხალძე",
      score: 50,
      classwork: 50,
      extraProjects: 0,
    },
   
  ],
  [
    { name: "ლადო ნიჟარაძე", score: 130, classwork: 100, extraProjects: 30 },
    { name: "ლუკა ფიფია", score: 130, classwork: 100, extraProjects: 30 },
    { name: "გიორგი ჩიღვინაძე", score: 65, classwork: 45, extraProjects: 20 },
    { name: "გურამ გელხაური", score: 100, classwork: 100, extraProjects: 0 },
    { name: "გელუკა გენებაშვილი", score: 110, classwork: 85, extraProjects: 30 },
    { name: "ლუკა ტოკლიკიშვილი", score: 160, classwork: 100, extraProjects: 60 },
    { name: "ნიკა მალაყმაძე", score: 100, classwork: 100, extraProjects: 0 },
    { name: "ლუკა ციხელაშვილი", score: 85, classwork: 85, extraProjects: 0 },
    { name: "ელენე გაფრინდაშვილი", score: 50, classwork: 50, extraProjects: 0 },
    { name: "ნიკოლოზ ქათამაძე", score: 100, classwork: 100, extraProjects: 0 },
    { name: "გიორგი უძილაური", score: 15, classwork: 15, extraProjects: 0 },
    { name: "გიორგი ქრისტესიაშვილი", score: 175, classwork: 175, extraProjects: 20 },
    { name: "ნიკა ბლიაძე", score: 90, classwork: 90, extraProjects: 0 },
    { name: "ლუკა შუკვანი", score: 145, classwork: 75, extraProjects: 70 },
    { name: "ანდრია ცაცუა", score: 100, classwork: 100, extraProjects: 0 },
    { name: "ლუკა კელეპტრიშვილი", score: 80, classwork: 80, extraProjects: 0 },
    { name: "ლუკა სუარიშვილი", score: 50, classwork: 50, extraProjects: 0 },
    { name: "დავით ლიპარტელიანი", score: 100, classwork: 100, extraProjects: 0 },
    { name: "გაბო დუმბაძე", score: 100, classwork: 100, extraProjects: 0 },
    { name: "ანა კაპანაძე", score: 85, classwork: 85, extraProjects: 0 },
    { name: "რეზი ხარებავა", score: 80, classwork: 80, extraProjects: 0 },
    { name: "ნინო ზარდიაშვილი", score: 100, classwork: 100, extraProjects: 0 },
    { name: "ზურა დავითაძე", score: 50, classwork: 50, extraProjects: 0 },
    { name: "დავით ქარაქუსოვი", score: 25, classwork: 25, extraProjects: 0 },
    { name: "ნიკოლოზ ანთაძე", score: 130, classwork: 70, extraProjects: 60 },
    { name: "გიორგი გურიელი", score: 35, classwork: 35, extraProjects: 0 },
    { name: "თორნიკე მღებლიშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "საბა ლაცაბიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა ოყროშიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა გვილავა", score: 80, classwork: 80, extraProjects: 0 },
    { name: "ლუკა პიტნავა", score: 80, classwork: 80, extraProjects: 0 },
    { name: "გიორგი კოსტავა", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა სურმანიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "რომან მაღრაძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკა მაღლაფერიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "პაატა ცუცქირიძე", score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკოლოზ მელიჯანაშვილი", score: 0, classwork: 0, extraProjects: 0 },
    { name: "დავით ბერკაცაშვილი", score: 0, classwork: 0, extraProjects: 0 },
  ],
  [{ "name": "გიორგი დათაშვილი", "score": 110, "classwork": 110, "extraProjects": 0 }, { "name": "ცოტნე გულბანი", "score": 45, "classwork": 45, "extraProjects": 0 }, { "name": "სანდრო სიუკაშვილი", "score": 100, "classwork": 100, "extraProjects": 0 }, { "name": "გიორგი ტლაშაძე", "score": 45, "classwork": 45, "extraProjects": 0 }, { "name": "გიორგი აბუაშვილი", "score": 100, "classwork": 100, "extraProjects": 0 }, { "name": "გიორგი მანაშვილი", "score": 100, "classwork": 100, "extraProjects": 0 }, { "name": "ლუკა მეტრეველი", "score": 45, "classwork": 45, "extraProjects": 0 }, { "name": "ლიზა ღიბრაძე", "score": 70, "classwork": 70, "extraProjects": 0 }, { "name": "ნიკოლოზ პეტრიაშვილი", "score": 70, "classwork": 70, "extraProjects": 0 }, { "name": "გიორგი ტატიშვილი", "score": 100, "classwork": 100, "extraProjects": 0 }, { "name": "ირაკლი ოზაშვილი", "score": 5, "classwork": 0, "extraProjects": 0 }, { "name": "აპოლონ ასანიძე", "score": 50, "classwork": 50, "extraProjects": 0 }, { "name": "თორნიკე ჟუჟნიაშვილიძე", "score": 80, "classwork": 80, "extraProjects": 0 }, { "name": "ბარბარე შარიქაძე", "score": 80, "classwork": 80, "extraProjects": 0 }, { "name": "რომიკო აბესაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "ჯაბა ბეგიაშვილი", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "საბა ბეგიაშვილი", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "უმარ აბუბაკაშვილი", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "დათო მიქელაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "ნათია კიკვაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "ბექა ბერაია", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "გიორგი ომანაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "გიორგი გამლდია", "score": 0, "classwork": 0, "extraProjects": 0 }],
];
