export const groupObject = [
  // ! 5

  [
    {
      name: "ალქესანდრე ჭანკვეტაძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ვაჩე კაკალაშვილი ",
      studentAttend: 0,
      help: 0,
      cameraOn: 0,
      answers: 0,
      score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ზაზა ბორისოვი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი ხუნდაძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი მამულაიძე ",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ნიკა მუსერიძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი გელაშვილი ",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი გოგოლაძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიორგი ჯოხაძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ილია ზაქარაიძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "გიგა ყიფიანი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "იოანე სარიშვილი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა სიჭინავა",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
    {
      name: "ლუკა ნავროზაშვილი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
      classwork: 0,
      extraProjects: 0,
    },
  ],
  // ! 6

  [{
    name: "საბა წიქარიშვილი",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 150,
    classwork: 50,
    extraProjects: 100,
  },
  {
    name: "შიო ელიკაშვილი",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 260,
    classwork: 120,
    extraProjects: 140,
  },
  {
    name: "თემო ველიჯანაშვილი",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 260,
    classwork: 90,
    extraProjects: 170,
  },
  {
    name: "ანდრია ღადუაშვილი",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
    classwork: 0,
    extraProjects: 0,
  },
  {
    name: "ნიკოლოზ ჩაგანავა",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 220,
    classwork: 90,
    extraProjects: 120,
  },
  {
    name: "ბუბა ებრალიძე",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 50,
    classwork: 50,
    extraProjects: 0,
  },
  {
    name: "ლუკა გიორგაძე",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 90,
    classwork: 90,
    extraProjects: 0,
  },
  {
    name: "დაჩი ჯაჯანაშვილი",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 240,
    classwork: 90,
    extraProjects: 150,
  },
  {
    name: "ბექა ბეჟანიშვილი",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 50,
    classwork: 50,
    extraProjects: 0,
  },
  {
    name: "გიგა ყიფიანი",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 50,
    classwork: 50,
    extraProjects: 0,
  },
  {
    name: "სანდრო სიდამონიძე",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 25,
    classwork: 25,
    extraProjects: 0,
  },
  {
    name: "ლაზრე ღოღობერიძე",
    studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0,
    classwork: 0,
    extraProjects: 0,
  },
  ],
  // ! 38

  [
    {
      name: "კონსტანტინე პაპავა",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 260,
      classwork: 160,
      extraProjects: 100,
    },
    {
      name: "კესანე ბრეგვაძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 80,
      classwork: 80,
      extraProjects: 0,
    },
    {
      name: "ლუკა დათიაშვილი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 180,
      classwork: 120,
      extraProjects: 60,
    },
    {
      name: "ლუკა რაზმაძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 80,
      classwork: 80,
      extraProjects: 0,
    },
    {
      name: "ანდრია ჯანეზაშვილი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 240,
      classwork: 140,
      extraProjects: 100,
    },
    {
      name: "ლუკა ოშორიზე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 150,
      classwork: 150,
      extraProjects: 0,
    },
    {
      name: "გიორგი წიკლაური",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 15,
      classwork: 15,
      extraProjects: 0,
    },
    {
      name: "ანარია დვალი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 80,
      classwork: 80,
      extraProjects: 0,
    },
    {
      name: "გუგა აკოლაშვილი",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 80,
      classwork: 80,
      extraProjects: 0,
    },
    {
      name: "დავიდ დუმბაძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 100,
      classwork: 100,
      extraProjects: 0,
    },
    {
      name: "დემეტრე ცეცხალძე",
      studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 50,
      classwork: 50,
      extraProjects: 0,
    },

  ],
  // ! 47
  [
    { name: "ლადო ნიჟარაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 155, classwork: 125, extraProjects: 30 },
    { name: "ლუკა ფიფია", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 160, classwork: 130, extraProjects: 30 },
    { name: "გიორგი ჩიღვინაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 140, classwork: 70, extraProjects: 70 },
    { name: "გურამ გელხაური", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 150, classwork: 120, extraProjects: 30 },
    { name: "გელუკა გენებაშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 125, classwork: 100, extraProjects: 30 },
    { name: "ლუკა ტოკლიკიშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 285, classwork: 125, extraProjects: 160 },
    { name: "ნიკა მალაყმაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 330, classwork: 130, extraProjects: 200 },
    { name: "ლუკა ციხელაშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 100, classwork: 100, extraProjects: 0 },
    { name: "ელენე გაფრინდაშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 80, classwork: 80, extraProjects: 0 },
    { name: "ნიკოლოზ ქათამაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 125, classwork: 125, extraProjects: 0 },
    { name: "გიორგი უძილაური", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 15, classwork: 15, extraProjects: 0 },
    { name: "გიორგი ქრისტესიაშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 210, classwork: 190, extraProjects: 20 },
    { name: "ნიკა ბლიაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 110, classwork: 110, extraProjects: 0 },
    { name: "ლუკა შუკვანი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 170, classwork: 100, extraProjects: 70 },
    { name: "ანდრია ცაცუა", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 125, classwork: 125, extraProjects: 0 },
    { name: "ლუკა კელაპტრიშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 100, classwork: 100, extraProjects: 0 },
    { name: "ლუკა სუარიშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 90, classwork: 90, extraProjects: 0 },
    { name: "დავით ლიპარტელიანი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 130, classwork: 130, extraProjects: 0 },
    { name: "გაბო დუმბაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 125, classwork: 125, extraProjects: 0 },
    { name: "ანა კაპანაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 100, classwork: 100, extraProjects: 0 },
    { name: "რეზი ხარებავა", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 110, classwork: 110, extraProjects: 0 },
    { name: "ნინო ზარდიაშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 100, classwork: 100, extraProjects: 0 },
    { name: "ზურა დავითაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 50, classwork: 50, extraProjects: 0 },
    { name: "დავით ქარაქუსოვი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 25, classwork: 25, extraProjects: 0 },
    { name: "ნიკოლოზ ანთაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 160, classwork: 100, extraProjects: 60 },
    { name: "გიორგი გურიელი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 70, classwork: 70, extraProjects: 0 },
    { name: "თორნიკე მღებლიშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "საბა ლაცაბიძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა ოყროშიძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა გვილავა", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 80, classwork: 80, extraProjects: 0 },
    { name: "ლუკა პიტნავა", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 110, classwork: 110, extraProjects: 0 },
    { name: "გიორგი კოსტავა", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "ლუკა სურმანიძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "რომან მაღრაძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკა მაღლაფერიძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "პაატა ცუცქირიძე", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "ნიკოლოზ მელიჯანაშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
    { name: "დავით ბერკაცაშვილი", studentAttend: 0, help: 0, cameraOn: 0, answers: 0, score: 0, classwork: 0, extraProjects: 0 },
  ],
  // ! 48
  [{ "name": "გიორგი დათაშვილი", "score": 150, "classwork": 150, "extraProjects": 0 }, { "name": "ცოტნე გულბანი", "score": 45, "classwork": 45, "extraProjects": 0 }, { "name": "სანდრო სიუკაშვილი", "score": 140, "classwork": 140, "extraProjects": 0 }, { "name": "გიორგი ტლაშაძე", "score": 80, "classwork": 80, "extraProjects": 0 }, { "name": "გიორგი აბუაშვილი", "score": 130, "classwork": 130, "extraProjects": 0 }, { "name": "გიორგი მანაშვილი", "score": 230, "classwork": 130, "extraProjects": 100 }, { "name": "ლუკა მეტრეველი", "score": 45, "classwork": 45, "extraProjects": 0 }, { "name": "ლიზა ღიბრაძე", "score": 110, "classwork": 110, "extraProjects": 0 }, { "name": "ნიკოლოზ პეტრიაშვილი", "score": 70, "classwork": 70, "extraProjects": 0 }, { "name": "გიორგი ტატიშვილი", "score": 130, "classwork": 130, "extraProjects": 0 }, { "name": "ირაკლი ოზაშვილი", "score": 5, "classwork": 0, "extraProjects": 0 }, { "name": "აპოლონ ასანიძე", "score": 50, "classwork": 50, "extraProjects": 0 }, { "name": "თორნიკე ჟუჟნიაშვილიძე", "score": 120, "classwork": 120, "extraProjects": 0 }, { "name": "ბარბარე შარიქაძე", "score": 110, "classwork": 110, "extraProjects": 0 }, { "name": "რომიკო აბესაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "ჯაბა ბეგიაშვილი", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "საბა ბეგიაშვილი", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "უმარ აბუბაკაშვილი", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "დათო მიქელაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "ნათია კიკვაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "ბექა ბერაია", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "გიორგი ომანაძე", "score": 0, "classwork": 0, "extraProjects": 0 }, { "name": "გიორგი გამლდია", "score": 0, "classwork": 0, "extraProjects": 0 }],
];
